//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBi.LostDoc.Repository.Web.Host.App_Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class LostDoc : global::System.Configuration.ApplicationSettingsBase {
        
        private static LostDoc defaultInstance = ((LostDoc)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LostDoc())));
        
        public static LostDoc Default {
            get {
                return defaultInstance;
            }
        }
    }
}
